name: My First workflow
on:
  pull_request:  
    branches:
      - main
    paths: 
      - 'doc/**' #globbing patterns. **/*.clj, src/**/*.clj, src/*.clj, *.clj
      - '**/*.clj'
  
  push:
    branches:
      - main
    paths:
      - '**/*.clj'

  workflow_dispatch: 
    inputs:
      homedrive:
        description: 'the home drive of the machine' 
        required: true

      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

      tag:
        description: 'Apply tag after successful run'
        type: boolean
        required: true

      environment:
        description: 'Environment to run test against'
        type: environment
        required: true

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello world"

      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: List files in a directory
        run: |
          echo The repository ${{ github.repository }} contains the following files
          tree
      
      - name: workflow inputs
        run: |
          echo "Homedrive: ${{inputs.homedrive}}"
          echo "Log level: ${{inputs.loglevel}}"
          echo "Tag source: ${{inputs.tag}}"
          echo "Environment: ${{inputs.environment}}"
        if: ${{github.event_name == 'workflow_dispatch'}}
