name: My First workflow
on:
  push: 
    branches:
      - main

  workflow_dispatch: 
    inputs:
      homedrive:
        description: 'the home drive of the machine' 
        required: true

      logLevel:
        description: 'Log level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

      tag:
        description: 'Apply tag after successful run'
        required: true

      environment:
        description: 'Environment to run test against'
        type: environment
        required: true

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello world"

      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: List files in a directory
        run: |
          echo The repository ${{ github.repository }} contains the following files
          tree
    
  

