name: My First workflow
on:
  push: 
    branches:
      - main

  workflow_dispatch: 

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello world"

      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: List files in a directory
        run: |
          echo The repository ${{ github.repository }} contains the following files
          tree
    
  

